import LocalizedStrings from 'react-native-localization'
export default strings = new LocalizedStrings({
    en: {
        question:'Question:',
        average_Rating:'Average Rating: ',
        no:'No:',
        yes:'Yes:',
        no_data:'No Data available',
        document_translate:'Documents Translated',
        count:'Count',
        logged_in_user:'Logged in User',
        users:'Users',
        sentence_count:'Sentence Count',
        total_Sentence_count:'Total Sentence Count (in K)',
        word_count:'Word Count',
        total_word_count:'Total Word Count (in K)',
        translate_language_share:'Translated Language Share',
        language_by_court:'Languages By Court',
        documents:'Documents',
        feedback:'Feedback',
        show_all:'Show All',
        last_month:'Last Month',
        last_week:'Last Week',
        last_day:'Last Day',
        custom_date:'Custom Date',
        from:'From',
        to:'To',
        submit:'Submit',
        Bengali:'Bengali',
        English:'English',
        Gujarati:'Gujarati',
        Hindi:'Hindi',
        Malayalam:'Malayalam',
        Marathi:'Marathi',
        Tamil:'Tamil',
        Telugu:'Telugu',
        Kannada:'Kannada',
        Punjabi:'Punjabi',
        till_today:'Till Today',
        message:'Message',
        no_of_ratings:'Number of Ratings for ',
        dashboard:'Dashboard',
        rating:' Rating',
        api_status:'api Status  ',
        suvas_text: 'Suvas',
        change_language: 'Change Language',
        done: 'Done',
        karnataka: 'Karnataka',
        telangana: 'Telangana',
        gujarat: 'Gujarat',
        west_bengal: 'West Bengal',
        maharashtra: 'Maharashtra',
        kerala: 'Kerala',
        haryana: 'Haryana',
        uttarakhand: 'Uttarakhand',
        tamilnadu: 'Tamilnadu',
        uttar_pradesh: 'Uttar Pradesh',
        andhra_pradesh: 'Andhra Pradesh',
        chhattisgarh: 'Chhattisgarh',
        rajasthan: 'Rajasthan',
        punjab: 'Punjab',
        himachal: 'Himachal',
        bihar: 'Bihar',
        jharkhand: 'Jharkhand'


    },

    hi:{
        question:'सवाल:',
        average_Rating:'औसत रेटिंग:',
        no:'नहीं:',
        yes:'हाँ:',
        no_data:'कोई डेटा उपलब्ध नहीं है',
        document_translate:'दस्तावेज़ अनुवादित हैं',
        count:'गणना',
        logged_in_user:'लॉग इन किया हुआ उपयोगकर्ता',
        users:'उपयोगकर्ता',
        sentence_count:'वाक्य गणना',
        total_Sentence_count:'कुल वाक्य गणना',
        word_count:'शब्द गणना',
        total_word_count:'कुल शब्द गणना',
        translate_language_share:'अनुवादित भाषा हिस्सा',
        language_by_court:'न्यायालय द्वारा भाषाएँ',
        documents:'दस्तावेज़',
        feedback:'प्रतिपुष्टि',
        show_all:'सब दिखाओ',
        last_month:'पिछले महीने',
        last_week:'पिछले सप्ताह',
        last_day:'आखरी दिन',
        custom_date:'कस्टम दिनांक',
        from:'से',
        to:'तक',
        submit:'प्रस्तुत करे',
        Bengali:'बंगाली',
        English:'अंग्रेज़ी',
        Gujarati:'गुजराती',
        Hindi:'हिंदी',
        Malayalam:'मलयालम',
        Marathi:'मराठी',
        Tamil:'तामिल',
        Telugu:'तेलुगू',
        Kannada:'कन्नड़',
        Punjabi:'पंजाबी',
        till_today:'आज तक',
        message:'संदेश',
        no_of_ratings:'रेटिंग की संख्या',
        dashboard:'डैशबोर्ड',
        rating:' रेटिंग',
        api_status:'एपीआई स्थिति  ',
        suvas_text: 'सुभाष',
        change_language: 'भाषा बदलो',
        done: 'संपन्न',
        karnataka: 'कर्नाटक',
        telangana: 'तेलंगाना',
        gujarat: 'गुजरात',
        west_bengal: 'पश्चिम बंगाल',
        maharashtra: 'महाराष्ट्र',
        kerala: 'केरल',
        haryana: 'हरियाणा',
        uttarakhand: 'उत्तराखंड',
        tamilnadu: 'तमिलनाडु',
        uttar_pradesh: 'उत्तर प्रदेश',
        andhra_pradesh: 'आंध्र प्रदेश',
        chhattisgarh: 'छत्तीसगढ़',
        rajasthan: 'राजस्थान',
        punjab: 'पंजाब',
        himachal: 'हिमाचल',
        bihar: 'बिहार',
        jharkhand: 'झारखंड'

    },

    mr:{
        question:'पप्रश्न',
        average_Rating:'सरासरी रेटिंग: ',
        no:'नाहीः',
        yes:'होय:',
        no_data:'माहिती उपलब्ध नाही',
        document_translate:'कागदपत्रांचे भाषांतर',
        count:'गणणे',
        logged_in_user:'लॉग इन वापरकर्ता',
        users:'वापरकर्ते',
        sentence_count:'वाक्य गणना',
        total_Sentence_count:'एकूण वाक्य गणना',
        word_count:'शब्द संख्या',
        total_word_count:'एकूण शब्द गणना',
        translate_language_share:'अनुवादित भाषेचा वाटा',
        language_by_court:'कोर्टाद्वारे भाषा',
        documents:'कागदपत्रे',
        feedback:'अभिप्राय',
        show_all:'सगळं दाखवा',
        last_month:'शेवटचा महिना',
        last_week:'शेवटचा आठवडा',
        last_day:'शेवटच्या दिवशी',
        custom_date:'सानुकूल तारीख',
        from:'पासून',
        to:'पर्यंत',
        submit:'प्रस्तुत करणे',
        Bengali:'बंगाली',
        English:'इंग्रजी',
        Gujarati:'गुजराती',
        Hindi:'हिंदी',
        Malayalam:'मल्याळम',
        Marathi:'मराठी',
        Tamil:'तमिळ',
        Telugu:'तेलगू',
        Kannada:'कन्नड',
        Punjabi:'पंजाबी',
        till_today:'आज पर्यंत',
        message:'संदेश',
        no_of_ratings:'साठी रेटिंगची संख्या ',
        dashboard:'डॅशबोर्ड',
        rating:' रेटिंग',
        api_status:'एपीआय स्थिती  ',
        suvas_text: 'सुभाष',
        change_language: 'भाषा बदला',
        done: 'पूर्ण झाले',
        karnataka: 'कर्नाटक',
        telangana: 'तेलंगाना',
        gujarat: 'गुजरात',
        west_bengal: 'पश्चिम बंगाल',
        maharashtra: 'महाराष्ट्र',
        kerala: 'केरल',
        haryana: 'हरियाणा',
        uttarakhand: 'उत्तराखंड',
        tamilnadu: 'तमिलनाडु',
        uttar_pradesh: 'उत्तर प्रदेश',
        andhra_pradesh: 'आंध्र प्रदेश',
        chhattisgarh: 'छत्तीसगढ़',
        rajasthan: 'राजस्थान',
        punjab: 'पंजाब',
        himachal: 'हिमाचल',
        bihar: 'बिहार',
        jharkhand: 'झारखंड'
    },

})